---
- name: Add mongo apt repository
  apt_repository:
    repo: deb https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse  # yamllint disable-line rule:line-length

- name: Install mongodb org shell
  apt:
    name: mongodb-org-shell
